apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
replicas:
- count: 3
  name: quarkus-demo
resources:
- ../../base/
images:
- name: quay.io/redhat-telco-adoption/quarkus-demo
  newTag: v1.0.6
